version: '3.8'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
    environment:
      DB_ADDRESS: "127.0.0.1/3306"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network

  db:
    image: mysql:8.0
    restart: always
    healthcheck:
      test: "exit 0"
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql
    ports:
      - '3007:3306'
    environment:
      MYSQL_ROOT_PASSWORD: dima94MYSQL
      MYSQL_DATABASE: ecom
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network: